#!/usr/bin/env bash
# Deny config access to any user who isn't root

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ "$SSH_USER" != "root" && $3 == plugin* ]]; then
  echo "You must be root to manage plugins."
  exit 1
fi

exit 0
